In [17]:
import h5py
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
%cd '/content/drive/My Drive/ML/CS114.K21.KHTN/Final'

/content/drive/My Drive/ML/CS114.K21.KHTN/Final


1. normal

In [5]:
normal_train = 'H5PY/train/train_normal.h5'
normal_test = 'H5PY/test/test_normal.h5'

In [6]:
data_normal_train = h5py.File(normal_train,'r')
data_normal_test  = h5py.File(normal_test,'r')

In [7]:
train_normal = data_normal_train['dataset']
test_normal = data_normal_test['dataset']

In [9]:
train_normal.shape

(13720, 3072)

In [10]:
test_normal.shape

(2400, 3072)

In [11]:
train_normal[0]

array([0.44313725, 0.45490196, 0.51372549, ..., 0.68235294, 0.7372549 ,
       0.76078431])

In [12]:
test_normal[0]

array([0.8627451 , 0.89019608, 0.88235294, ..., 0.69803922, 0.7254902 ,
       0.74509804])

In [15]:
data_normal_train.close()
data_normal_test.close()

2. local binary

In [18]:
lbps_train = 'H5PY/train/train_lbps.h5'
lbps_test = 'H5PY/test/test_lbps.h5'

In [20]:
data_lbps_train = h5py.File(lbps_train,'r')

In [22]:
train_lbps = data_lbps_train['dataset']

In [23]:
train_lbps.shape

(13720, 26)

In [24]:
train_lbps[0]

array([0.12890625, 0.07910156, 0.05175781, 0.03222656, 0.01367187,
       0.01171875, 0.00878906, 0.00390625, 0.00292969, 0.00097656,
       0.00195312, 0.        , 0.00097656, 0.        , 0.00097656,
       0.015625  , 0.00195312, 0.02539062, 0.        , 0.00683594,
       0.00488281, 0.01269531, 0.00585937, 0.01464844, 0.01660156,
       0.55761719])

In [21]:
data_lbps_test  = h5py.File(lbps_test,'r')

OSError: ignored

3.hog

In [25]:
hog_train = 'H5PY/train/train_hog.h5'
hog_test = 'H5PY/test/test_hog.h5'

In [27]:
data_hog_train = h5py.File(hog_train,'r')

In [29]:
train_hog = data_hog_train['dataset']

In [30]:
train_hog.shape

(13720, 144)

In [31]:
train_hog[0]

array([0.06922354, 0.044602  , 0.02313497, 0.00551059, 0.01469007,
       0.0081654 , 0.0126666 , 0.01964391, 0.00582791, 0.04791128,
       0.02800821, 0.0202543 , 0.01383986, 0.04417375, 0.06641278,
       0.05801535, 0.02266396, 0.03417181, 0.03361994, 0.00814857,
       0.01166392, 0.00596107, 0.01401346, 0.00960734, 0.03052328,
       0.05339545, 0.07586397, 0.04788313, 0.03377956, 0.01201811,
       0.01064783, 0.0265735 , 0.01547024, 0.01703647, 0.02036494,
       0.03450918, 0.03685444, 0.02154454, 0.01558006, 0.01064594,
       0.03397944, 0.0510862 , 0.04462671, 0.01743363, 0.02628573,
       0.0290529 , 0.0229808 , 0.02560426, 0.00750821, 0.01399193,
       0.02309237, 0.03792577, 0.05209099, 0.02464661, 0.03683278,
       0.025984  , 0.0092446 , 0.00819055, 0.02044094, 0.01190006,
       0.01310484, 0.01566517, 0.02654524, 0.08013477, 0.15809749,
       0.02219357, 0.02013054, 0.01539381, 0.01500143, 0.01281275,
       0.00514985, 0.0082442 , 0.03229559, 0.00782758, 0.01120

In [28]:
data_hog_test  = h5py.File(hog_test,'r')

OSError: ignored

label

In [51]:
train_label = 'H5PY/train/labels_train.h5'
test_label  = 'H5PY/test/labels_test.h5'

In [38]:
label_train  = h5py.File(train_label,'r')

In [40]:
train = label_train['dataset'] 

In [41]:
train.shape

(13720,)

In [53]:
label_test  = h5py.File(test_label,'r')

In [54]:
test = label_test['dataset']

In [55]:
test.shape

(2400,)